development:
  adapter: postgresql
  encoding: utf8
  database: lens
  pool: 5
  username: postgres
  password: 
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: lens_test
  pool: 5
  username: dev
  password:
  host: localhost
  prepared_statements: false

production:
  adapter: postgresql
  encoding: utf8
  database: lens
  pool: 5
  username: dev
  password:
  host: localhost

staging:
  adapter: postgresql
  encoding: utf8
  database: lens
  pool: 5
  username: dev
  password:
  host: localhost
